name: Run Tests

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.2'

      - name: Run Tests
        run: |
          make test